PUT http://localhost:9090/events/4
content-type: application/json

{
  "name": "Updated test event",
  "description": "A test event",
  "location": "Test location (updated!)",
  "dateTime": "2024-01-03T15:30:00.000Z"
}